### ISSUE TITLE
On windows machine I'm got the below error for relay-modern

### ISSUE THREAD

**Issue by softglance** [nodkz/northwind-relay-example-app#6]
Relay Watcher was exited!
{ Error: spawn yarn ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'relay', '--', '--watch' ] }
Relay Watcher was exited!

**Comment by nodkz** [comment]
Try to change https://github.com/nodkz/relay-northwind-app/blob/master/tools/startDevServers.js#L104
```diff
- const childProcess = spawn('yarn', ['relay', '--', '--watch'], {
+ const childProcess = spawn('npm', ['run', 'relay', '--', '--watch'], {
```

If it will work on your machine, please open PR with this fix.
Tnx.

**Comment by nodkz** [comment]
Try to pull last changes from master and run them
